const express = require('express');
const path = require('path');


//HTML ROUTES 
// GET NOTES AND INDEX. HTML
//API ROUTES
//GETAPI NOTES AND DB.JSON AND RETURN ALL SAVED NOTES
//POST API NOTES RECEIVE NEW NOTES TO SAVE ON BODY AND ADD TO DB JSON & RETURN TO CLIENT
//UNIQUE ID FOR EACH NOTE .. NPM PACKAGES
//BONUS: DELETE API RECEIVVE A QUERY PARAM WITH ID OF NOTE TO DELETE